SHOW DATABASES;
CREATE DATABASE TEST1;
USE TEST1;
CREATE TABLE TEST1 ( 
ID INT(10),
FIRST_NAME VARCHAR(10),
LAST_NAME VARCHAR(10),
CITY VARCHAR(10)
);

SELECT * FROM TEST1;
INSERT INTO TEST1 VALUES
(1,'JALPA','DESAI','ANAND'),
(2,'ANAJANA','AJAY','BARODA'),
(3,'NILAM','PATEL','ABAD'),
(4,'SIDDHANT','SHAH','ABAD'),
(5,'VIDHI','SHARMA','BARODA'),
(6,'DIVYA','OZA','GNAGAR')


SELECT * FROM TEST1 WHERE FIRST_NAME = 'JALPA';
SELECT * FROM TEST1 WHERE ID < 5;

SELECT * FROM TEST1 WHERE FIRST_NAME LIKE 'A%';
SELECT * FROM TEST1 WHERE FIRST_NAME LIKE '%A';
SELECT * FROM TEST1 WHERE LENGTH(FIRST_NAME) = 5;
SELECT * FROM TEST1 WHERE CITY = 'ANAND' OR CITY = 'BARODA';

CREATE DATABASE TEST2;
USE TEST2;

CREATE TABLE IF NOT EXISTS TEST2 ( 
TEST_ID INT AUTO_INCREMENT,
TEST_NAME VARCHAR(30),
TEST_MAILID VARCHAR(30),
TEST_ADDRESS VARCHAR(30),
PRIMARY KEY (TEST_ID)
);

SELECT * FROM TEST2;
INSERT INTO TEST2(TEST_NAME,TEST_MAILID,TEST_ADDRESS) VALUES
('JAL','JALPA@GAMIL.COM','BARODA'),
('JAL','JALPA@GAMIL.COM','BARODA'),
('JAL','JALPA@GAMIL.COM','BARODA'),
('JAL','JALPA@GAMIL.COM','BARODA')

CREATE DATABASES TEST4;
USE TEST4;
CREATE TABLE IF NOT EXISTS TEST4 ( 
TEST_ID INT,
TEST_NAME VARCHAR(30),
TEST_MAILID VARCHAR(30),
TEST_ADDRESS VARCHAR(30),
TEST_SALARY INT CHECK(TEST_SALARY < 10000)
);
SELECT * FROM TEST4;


INSERT INTO TEST4 VALUES
(1,'JALPA','JALPA@GMAIL.COM','ANAND',6000),
(2,'ANJU','ANJU@GMAIL.COM','SURAT',5000),
(3,'JASS','JASS@GMAIL.COM','AHMEDABAD',7000);



SHOW DATABASES;
CREATE DATABASE TEST5;
USE TEST5;

CREATE TABLE IF NOT EXISTS TEST5(
TEST_ID int,
TEST_NAME VARCHAR(30),
TEST_MAILID VARCHAR(30),
TEST_ADDRESS VARCHAR(30) CHECK (TEST_ADDRESS = 'BANGLORE'),
TEST_SALARY int);

INSERT INTO TEST5(TEST_ID,TEST_NAME,TEST_MAILID,TEST_ADDRESS,TEST_SALARY) VALUES
(100,'JAL','JALPA@GMAIL.COM','BANGLORE',5000);
INSERT INTO TEST5(TEST_ID,TEST_NAME,TEST_MAILID,TEST_ADDRESS,TEST_SALARY) VALUES
(110,'ABC','JALPA@GMAIL.COM','BARODA',6000);
SELECT * FROM TEST5;

SHOW DATABASES;
CREATE DATABASE TEST6;
USE TEST6;

CREATE TABLE IF NOT EXISTS TEST6(
TEST_ID INT NOT NULL AUTO_INCREMENT,
TEST_NAME VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN',
TEST_MAILID VARCHAR(30) UNIQUE NOT NULL,
TEST_ADDRESS VARCHAR(30) CHECK (TEST_ADDRESS = 'BANGLORE') NOT NULL,
TEST_SALARY INT CHECK (TEST_SALARY > 10000) NOT NULL,
PRIMARY KEY (TEST_ID));

SELECT * FROM TEST6;

INSERT INTO TEST6(TEST_NAME,TEST_MAILID,TEST_ADDRESS,TEST_SALARY) VALUES
('JALPA','JALPA1@GMAIL.COM','BANGLORE',20000);
INSERT INTO TEST6(TEST_MAILID,TEST_ADDRESS,TEST_SALARY) VALUES
('ABC@GMAIL.COM','BANGLORE',30000);

INSERT INTO TEST6(TEST_ID,TEST_NAME,TEST_MAILID,TEST_ADDRESS,TEST_SALARY) VALUES
(200,'JAL','1JALPA@GMAIL.COM','BANGLORE',600000);

INSERT INTO TEST6(TEST_ID,TEST_MAILID,TEST_ADDRESS,TEST_SALARY) VALUES
(198,'3JALPA@GMAIL.COM','BANGLORE',60000);