CREATE DATABASE DRESS_DATA;
USE DRESS_DATA;

CREATE TABLE DRESS1(
Dress_ID VARCHAR (50),
Style	VARCHAR (50),
Price VARCHAR (50),	
Rating VARCHAR (50),	
Size VARCHAR (50),
Season VARCHAR (50),	
NeckLine VARCHAR (50),	
SleeveLength VARCHAR (50),	
waiseline VARCHAR (50),	
Material VARCHAR (50),	
FabricType VARCHAR (50),	
Decoration VARCHAR (50),	
Pattern_Type VARCHAR (50),	
Recommendation VARCHAR (50)
);

SELECT * FROM DRESS1;

LOAD DATA INFILE
'C:/AttributeDataSet.csv'
INTO TABLE DRESS1
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS 

CREATE DATABASE CSVKIT;
USE CSVKIT;

CREATE TABLE sales_data_final (
	order_id VARCHAR(15) NOT NULL, 
	order_date VARCHAR(14) NOT NULL, 
	ship_date VARCHAR(14) NOT NULL, 
	ship_mode VARCHAR(14) NOT NULL, 
	customer_name VARCHAR(22) NOT NULL, 
	segment VARCHAR(11) NOT NULL, 
	state VARCHAR(36) NOT NULL, 
	country VARCHAR(32) NOT NULL, 
	market VARCHAR(6) NOT NULL, 
	region VARCHAR(14) NOT NULL, 
	product_id VARCHAR(16) NOT NULL, 
	category VARCHAR(15) NOT NULL, 
	sub_category VARCHAR(11) NOT NULL, 
	product_name VARCHAR(127) NOT NULL, 
	sales DECIMAL(38, 0) NOT NULL, 
	quantity DECIMAL(38, 0) NOT NULL, 
	discount DECIMAL(38, 3) NOT NULL, 
	profit DECIMAL(38, 5) NOT NULL, 
	shipping_cost DECIMAL(38, 2) NOT NULL, 
	order_priority VARCHAR(8) NOT NULL, 
	year DECIMAL(38, 0) NOT NULL
);

SELECT * FROM sales_data_final LIMIT 5;

LOAD DATA INFILE
'C:/sales_data_final.csv'
INTO TABLE sales_data_final
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS 

SET SESSION SQL_MODE = '';

SELECT STR_TO_DATE(ORDER_DATE,'%m-%d-%y') FROM sales_data_final;
ALTER TABLE sales_data_final
ADD COLUMN ORDER_DATE_NEW DATE AFTER ORDER_DATE;

UPDATE sales_data_final
SET ORDER_DATE_NEW = STR_TO_DATE(ORDER_DATE,'%m-%d-%Y');

SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

SELECT STR_TO_DATE(SHIP_DATE,'%m-%d-%y') FROM sales_data_final;

ALTER TABLE sales_data_final
ADD COLUMN SHIP_DATE_NEW DATE AFTER SHIP_DATE;

UPDATE sales_data_final
SET SHIP_DATE_NEW = STR_TO_DATE(SHIP_DATE,'%m-%d-%Y');

SELECT * FROM sales_data_final WHERE SHIP_DATE_NEW = '2011-01-05'
SELECT * FROM sales_data_final WHERE SHIP_DATE_NEW > '2011-01-05'
SELECT * FROM sales_data_final WHERE SHIP_DATE_NEW < '2011-01-05'
SELECT * FROM sales_data_final WHERE SHIP_DATE_NEW BETWEEN '2011-01-05' AND '2011-08-30'
SELECT NOW()
SELECT YEAR(NOW())
SELECT CURDATE()
SELECT CURTIME()

SELECT DATE_SUB(NOW() , INTERVAL 1 WEEK)
SELECT DATE_SUB(NOW() , INTERVAL 30 DAY)
SELECT DATE_SUB(NOW() , INTERVAL 30 YEAR)

SELECT * FROM SALES_DATA_FINAL WHERE SHIP_DATE_NEW < DATE_SUB(NOW() , INTERVAL 1 WEEK)
SELECT DAYNAME('2022-09-20 21:10:30')

SELECT * FROM sales_data_final LIMIT 5;


ALTER TABLE sales_data_final
MODIFY COLUMN YEAR DATETIME;

ALTER TABLE sales_data_final
ADD COLUMN MONTH_NEW1 INT;

ALTER TABLE sales_data_final
ADD COLUMN DAY_NEW1 INT;

ALTER TABLE sales_data_final
ADD COLUMN YEAR_NEW1 INT;


UPDATE SALES_DATA_FINAL SET MONTH_NEW1 = MONTH(ORDER_DATE_NEW);
UPDATE SALES_DATA_FINAL SET DAY_NEW1 = DAY(ORDER_DATE_NEW);
UPDATE SALES_DATA_FINAL SET YEAR_NEW1 = YEAR(ORDER_DATE_NEW);

ALTER TABLE SALES_DATA_FINAL ADD COLUMN FLAG1 DATE AFTER ORDER_ID;
UPDATE SALES_DATA_FINAL SET FLAG1 = NOW();

SELECT SUM(SALES),YEAR FROM  SALES_DATA_FINAL GROUP BY YEAR ORDER BY SUM(SALES) ASC;

ALTER TABLE SALES_DATA_FINAL ADD COLUMN FLAG_NEW12 VARCHAR (10);
UPDATE SALES_DATA_FINAL SET FLAG_NEW12 = IF(DISCOUNT > 0,'YES', 'NO')

SELECT AVG(QUANTITY),YEAR FROM  SALES_DATA_FINAL GROUP BY YEAR ORDER BY AVG(QUANTITY) ASC;

ALTER TABLE SALES_DATA_FINAL DROP COLUMN MONTH_NEW;