SHOW DATABASES;
CREATE DATABASE TEST22;
USE TEST22;

CREATE TABLE CUSTOMER(
CUSTOMER_ID INT NOT NULL AUTO_INCREMENT,
CUSTOMER_NAME VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN',
CUSTOMER_MAILID VARCHAR(30) UNIQUE NOT NULL,
CUSTOMER_CITY VARCHAR(30) NOT NULL,
CUSTOMER_AMOUNT INT CHECK (CUSTOMER_AMOUNT > 10000) NOT NULL,
PRIMARY KEY (CUSTOMER_ID));

SELECT * FROM CUSTOMER;

DROP TABLE CUSTOMER;
INSERT INTO CUSTOMER(CUSTOMER_NAME,CUSTOMER_MAILID,CUSTOMER_CITY,CUSTOMER_AMOUNT) VALUES
('SID','SID@GMAIL.COM','BARODA',20000),
('VIDHI','VIDHI@GMAIL.COM','AHMEDABAD',30000),
('DIVYA','DIVYA@GMAIL.COM','GANDHINAGAR',35000),
('TEJAL','TEJAL@GMAIL.COM','AHMEDABAD',40000),
('SAPAN','SAPAN@GMAIL.COM','BARODA',50000);