CREATE DATABASE LOOPPP;
USE LOOPPP;
CREATE TABLE LOOP_TABLE(VAL INT);
#CREATE LOOP
DELIMITER $$
CREATE PROCEDURE INSERT_DATA()
BEGIN
SET @VAR = 10;
GENERATE_DATA : LOOP
INSERT INTO LOOP_TABLE VALUES (@VAR);
SET @VAR = @VAR + 1;
IF @VAR = 100 THEN
      LEAVE GENERATE_DATA;
END IF;
END LOOP GENERATE_DATA;
END $$

CALL INSERT_DATA();
SELECT * FROM LOOP_TABLE;

#2VARIABLES AND 2 LOOPS
CREATE TABLE LOOP_TABLE123(VAL INT, MULTI INT);
DELIMITER $$
CREATE PROCEDURE INSERT_DATA123()
BEGIN
SET @VAR = 10, @VAR1 = 10;
GENERATE_DATA : LOOP
INSERT INTO LOOP_TABLE123 VALUES (@VAR,@VAR1);
SET @VAR = @VAR + 1;
IF @VAR = 50 THEN
      LEAVE GENERATE_DATA;
END IF;
SET @VAR1 = @VAR * 2;
IF @VAR1 = 50 THEN
      LEAVE GENERATE_DATA;
END IF;
END LOOP GENERATE_DATA;
END $$

CALL INSERT_DATA123();
SELECT * FROM LOOP_TABLE123;