SHOW DATABASES;
USE SAKILA;
SELECT * FROM CUSTOMER;
SELECT * FROM CITY;
SELECT ADDRESS_ID,FIRST_NAME,LAST_NAME FROM CUSTOMER;
SELECT DISTINCT STORE_ID FROM CUSTOMER;
SELECT DISTINCT ACTIVE FROM CUSTOMER;
SELECT * FROM CUSTOMER WHERE FIRST_NAME = 'MARIA';
SELECT FIRST_NAME, LAST_NAME FROM CUSTOMER WHERE FIRST_NAME = 'MARIA';
SELECT * FROM CUSTOMER WHERE FIRST_NAME = 'RUTH';
SELECT * FROM CUSTOMER WHERE STORE_ID = '1';
SELECT * FROM CUSTOMER WHERE ADDRESS_ID > '10';
SELECT * FROM CUSTOMER LIMIT 5;
SELECT * FROM CUSTOMER WHERE ADDRESS_ID < 20 LIMIT 3;
SELECT CUSTOMER_ID,FIRST_NAME,LAST_NAME FROM CUSTOMER WHERE CUSTOMER_ID BETWEEN 20 AND 25;
SELECT FIRST_NAME, LAST_NAME, EMAIL, ADDRESS_ID FROM CUSTOMER WHERE FIRST_NAME = 'JOAN' AND LAST_NAME = 'COOPER';
SELECT FIRST_NAME, LAST_NAME, EMAIL, ADDRESS_ID FROM CUSTOMER WHERE FIRST_NAME = 'MARIA' OR LAST_NAME = 'DAVIS';

SELECT * FROM CUSTOMER;
UPDATE CUSTOMER SET FIRST_NAME = 'SID' WHERE LAST_NAME = 'SMITH';
SELECT * FROM CUSTOMER WHERE FIRST_NAME = 'SID';
UPDATE CUSTOMER SET FIRST_NAME = 'JALPA' WHERE LAST_NAME = 'WILLIAMS';
SELECT * FROM CUSTOMER WHERE FIRST_NAME = 'JALPA';

SELECT * FROM CUSTOMER WHERE NOT STORE_ID = 2;

SELECT FIRST_NAME, LAST_NAME, EMAIL FROM CUSTOMER ORDER BY FIRST_NAME DESC;
SELECT FIRST_NAME, LAST_NAME, ADDRESS_ID FROM CUSTOMER ORDER BY ADDRESS_ID ASC;
SELECT FIRST_NAME, LAST_NAME, EMAIL FROM CUSTOMER ORDER BY FIRST_NAME ASC LIMIT 10;
SELECT FIRST_NAME, LAST_NAME, EMAIL, ADDRESS_ID FROM CUSTOMER ORDER BY ADDRESS_ID;

SELECT * FROM CUSTOMER LIMIT 10;
SELECT ADDRESS_ID FROM CUSTOMER WHERE STORE_ID = 1 ORDER BY ADDRESS_ID DESC LIMIT 3;

SELECT MIN(ADDRESS_ID) FROM CUSTOMER;
SELECT MAX(ADDRESS_ID) FROM CUSTOMER;
SELECT SUM(ADDRESS_ID) FROM CUSTOMER;
SELECT AVG(ADDRESS_ID) FROM CUSTOMER;
SELECT COUNT(*) FROM CITY;

SELECT FIRST_NAME, LAST_NAME, EMAIL FROM CUSTOMER WHERE ADDRESS_ID = (SELECT MIN(ADDRESS_ID) FROM CUSTOMER);

SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE 'R%';
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE '%A';
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE '%OR%';
SELECT * FROM CUSTOMER WHERE LAST_NAME LIKE '%PR%';
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE 'A_____%'; /* 5 UNDERSCORE MEANS 5 OR MORE LETTERS */
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE 'A_____';  /* FOR FIXED LENGTH OF LETTERS */
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE 'A%' AND LENGTH(FIRST_NAME) = 6;
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE 'A%O';
SELECT * FROM CUSTOMER WHERE CUSTOMER_ID NOT IN (1,2,3);

SHOW DATABASES;
USE SAKILA;
SELECT STORE_ID, COUNT(STORE_ID) FROM CUSTOMER GROUP BY STORE_ID;
SELECT ACTIVE, COUNT(CUSTOMER_ID) FROM CUSTOMER GROUP BY ACTIVE;

SHOW DATABASES;
USE WORLD;
SELECT * FROM COUNTRY;
SELECT COUNT(*) FROM COUNTRY;
SELECT * FROM COUNTRY WHERE POPULATION = '0';
SELECT MIN(POPULATION) FROM COUNTRY;
SELECT MAX(POPULATION) FROM COUNTRY;

SELECT SUM(POPULATION),CONTINENT FROM COUNTRY GROUP BY CONTINENT;
SELECT * FROM COUNTRY WHERE NAME = 'ARMENIA';
SELECT NAME, CONTINENT, REGION, POPULATION FROM COUNTRY WHERE POPULATION = (SELECT MIN(POPULATION) FROM COUNTRY); 
SELECT SUM(POPULATION),CONTINENT FROM COUNTRY GROUP BY CONTINENT ORDER BY SUM(POPULATION) ASC;