CREATE DATABASE TRIGGER_1;
USE TRIGGER_1;

CREATE TABLE COURSE2(
COURSE_ID INT,
COURSE_DESC VARCHAR(50),
COURSE_MENTOR VARCHAR(60),
COURSE_PRICE INT,
COURSE_DISCOUNT INT,
CREATE_DATE DATE,
USER_INFO VARCHAR(50));

SELECT USER();
SELECT SYSDATE();

#REFERENCE TABLE
CREATE TABLE REF_COURSE(
RECORD_INSERT_DATE DATE,
RECORD_INSERT_USER VARCHAR(50));

SELECT * FROM REF_COURSE;

#TRIGGER
DELIMITER //
CREATE TRIGGER COURSE_BEFORE_INSERT
BEFORE INSERT
ON COURSE2 FOR EACH ROW
BEGIN
    DECLARE USER_VAL VARCHAR(50);
    SET NEW.CREATE_DATE = SYSDATE();
    SELECT USER() INTO USER_VAL;
    SET NEW.USER_INFO = USER_VAL;
    
    INSERT INTO REF_COURSE VALUES(SYSDATE(), USER_VAL);
END; //
#TRIGGER CREATED NOW INSERT VALUES AND CHECK

INSERT INTO COURSE2 (COURSE_ID, COURSE_DESC, COURSE_MENTOR, COURSE_PRICE, COURSE_DISCOUNT)
VALUE (101,'FSDA','ALPA',1000,10);
#WE RAN IT 3 TIMES

SELECT * FROM COURSE2;


CREATE TABLE TEST1(
C1 VARCHAR(50),
C2 DATE,
C3 INT);

CREATE TABLE TEST2(
C1 VARCHAR(50),
C2 DATE,
C3 INT);

CREATE TABLE TEST3(
C1 VARCHAR(50),
C2 DATE,
C3 INT);

#CREATE TRIGGER TO UPDATE OTHER TABLES
DELIMITER //
CREATE TRIGGER TO_UPDATE_OTHERS
BEFORE INSERT ON TEST1 FOR EACH ROW
BEGIN
    INSERT INTO TEST2 VALUES('XYZ',SYSDATE(),123354);
    INSERT INTO TEST3 VALUES('ABC123',SYSDATE(),2366);
END; //
    
    
INSERT INTO TEST1 VALUES('ABC',SYSDATE(),234234);
INSERT INTO TEST1 VALUES('JALPA',SYSDATE(),234234);

SELECT * FROM TEST1;
SELECT * FROM TEST2;
SELECT * FROM TEST3;

#FOR NEXT TRIGGER VALUE OF MK12 SO IT CAN DELETE IT FROM TEST3
INSERT INTO TEST3 VALUES('MK12',SYSDATE(),11111);
DELIMITER //
CREATE TRIGGER TO_UPDATE_OTHERS_TABLE
AFTER INSERT ON TEST1 FOR EACH ROW
BEGIN
   UPDATE TEST2 SET C1 = 'JALPA' WHERE C1 = 'XYZ';
   DELETE FROM TEST3 WHERE C1 = 'MK12';
END; //

INSERT INTO TEST1 VALUES ('HARSH',SYSDATE(),977897);

#TRIGGER FOR AFTER DELETION
DELIMITER //
CREATE TRIGGER TO_DELETE_OTHER_TABLE
AFTER DELETE ON TEST1 FOR EACH ROW
BEGIN
     INSERT INTO TEST3 VALUES('AFTER DELETE',SYSDATE(),43547);
END; //

SELECT * FROM TEST1;
DELETE FROM TEST1 WHERE C1 ='HARSH';
SELECT * FROM TEST3;

#BEFORE DELETION
DELIMITER //
CREATE TRIGGER TO_DELETE_OTHERS_BEFORE
BEFORE DELETE ON TEST1 FOR EACH ROW 
BEGIN 
     INSERT INTO TEST3 VALUES('BEFORE DELETE',SYSDATE(),435457);
END; //

DELIMITER //
CREATE TRIGGER TO_DELETE_OTHERS_BEFORE_OBSERVATION
BEFORE DELETE ON TEST1 FOR EACH ROW 
BEGIN 
     INSERT INTO TEST2(C1,C2,C3) VALUES(OLD.C1,OLD.C2,OLD.C3);
END; //

DELETE FROM TEST1 WHERE C1 ='JALPA';
SELECT * FROM TEST2;
SELECT * FROM TEST3;

#UPDATE
DELIMITER //
CREATE TRIGGER TO_UPDATE_OTHERS1
AFTER UPDATE ON TEST1 FOR EACH ROW
BEGIN
    INSERT INTO TEST3(C1,C2,C3) VALUES('X',SYSDATE(),786);
END; //

SELECT * FROM TEST1;
INSERT INTO TEST1 VALUES('JJALPA',SYSDATE(),234354);
UPDATE TEST1 SET C1 = 'ABC@123' WHERE C1 = 'JJALPA';
SELECT * FROM TEST3;

DELIMITER //
CREATE TRIGGER TO_UPDATE_OTHERS_BEFORE1
BEFORE UPDATE ON TEST1 FOR EACH ROW
BEGIN
   INSERT INTO TEST2(C1,C2,C3) VALUES(NEW.C1,NEW.C2,NEW.C3);
END; //

INSERT INTO TEST1 VALUES('JJALPA',SYSDATE(),234354);
UPDATE TEST1 SET C1 = 'INSERT NEW' WHERE C1 = 'JJALPA';
SELECT * FROM TEST2;


