CREATE DATABASE TRIGGER_TASK;
USE TRIGGER_TASK;

CREATE TABLE TASK(
NAME VARCHAR(20),
MAIL_ID VARCHAR(25),
PHONE_NUMBER INT,
ADDRESS VARCHAR(50),
USERS_SYS VARCHAR(50),
TIME_SYS DATE,
SALARY DECIMAL(10,2),
INCENTIVE DECIMAL(10,2),
FINAL_SALARY DECIMAL(10,2)
);

SELECT * FROM TASK;

DELIMITER //
CREATE TRIGGER CALCULATE_FINAL_SALARY
BEFORE INSERT 
ON TASK FOR EACH ROW
BEGIN
     IF LEFT(NEW.NAME, 1) = 'S' THEN
     SET NEW.FINAL_SALARY = NEW.SALARY + NEW.INCENTIVE;
     END IF;
END; //

INSERT INTO TASK (NAME, MAIL_ID,PHONE_NUMBER,ADDRESS,SALARY,INCENTIVE)
VALUES ('SIDDHANT','SID@GMAIL.COM',999999999,'XXYYYZZZ',500000,100000);

INSERT INTO TASK (NAME, MAIL_ID,PHONE_NUMBER,ADDRESS,SALARY,INCENTIVE)
VALUES ('VIDHI','VIDHI@GMAIL.COM',99999889,'AAABBBCCC',600000,100000);


SELECT * FROM TASK;